### PR TITLE
restyle answers, comments, and make them toggle

### PR DESCRIPTION
**Pull request by rayanb**
@trevornelson @leoarogers Hey guys I have changed the comments form so that each toggles if the user wants to comment ...

### CODE REVIEW

**Comment by rayanb** [comment]
Trevor don't we have the ability to create a question on the website ?

2015-03-22 16:05 GMT-04:00 Trevor Nelson notifications@github.com:

**Comment by trevornelson** [comment]
Yeah, the ask link at the top of the navbar takes you to the question#new action and you can create a question there.

-----Original Message-----

**Comment by rayanb** [comment]
It's redirecting to an error

**Comment by leoarogers** [comment]
i’m seeing the same thing. Looks like there’s an issue with the comment_karma method.

**Pull request merged**
