### PR TITLE
Tn/voting functionality

### PR DESCRIPTION
**Pull request by trevornelson**
@rayanb @leoarogers finished the voting functionality and initial answer/question sorting.

### CODE REVIEW

**Comment by trevornelson** [comment]
@rayan @leoarogers also, after this is merged you'll have to rebase for it to work right. Somehow turbolinks was enabled even though I could've sworn we had that flag on rails new. Anyway, it was messing with my JS, so I stripped it out.

**Comment by rayanb** [comment]
Is there anything left to do ??

2015-03-21 19:26 GMT-04:00 Trevor Nelson notifications@github.com:

**Comment by trevornelson** [comment]
@rayanb I think that we have all of the user stories checked off at this point. I'm just going to edit some things I did yesterday that could be done a bit less sloppily, and maybe add some styling finishing touches. I think it also might make sense to toy with the category input on the create question form. Having the added category_name field kind of defeats the purpose of having the categories table in the db. I think having a <select> dropdown of the existing categories would be a bit more succinct.

**Comment by rayanb** [comment]
I agree tell me if you need me to work on something

**Pull request merged**
